# Site settings
title: Chris Watts
email: chris.watts.t@gmail.com
url: https://seawatts.github.io
description: "This is a site to show off my portfolio."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Chris Watts
  location: Location
  social: Around the Web

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/seawatts
  - title: linkedin
    url: https://www.linkedin.com/in/christwatts
  - title: github
    url: http://github.com/seawatts

# Postal address (add as many lines as necessary)
address:
  - line: Seattle, WA

# Build settings
markdown: kramdown
permalink: pretty
